services:
  gtmotive.estimate.microservice.host:
    image: ${DOCKER_REGISTRY-}gtmotiveestimatemicroservicehost
    build:
      context: .
      dockerfile: GtMotive.Estimate.Microservice.Host/Dockerfile
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand({ping:1})\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mongo-data:
    name: gtmotive_mongo_data

networks:
  app-network:
    driver: bridge
